build:
    environment:
        php:
            version: 7.1.12
    dependencies:
        before:
            - sudo composer self-update && composer --version
filter:
    excluded_paths:
        - tests/*