build:
    environment:
        php:
            version: 7.0.12
    dependencies:
        before:
            - sudo composer self-update && composer --version
            - composer global require "fxp/composer-asset-plugin:1.*"
filter:
    excluded_paths:
        - tests/*