<?php

use Ffcms\Core\Migrations\MigrationInterface;
use Ffcms\Core\Migrations\Migration;

/**
 * Class update_cms_310
 */
class update_cms_310 extends Migration implements MigrationInterface
{
    /**
     * Implement new update changes
     * @return void
     */
    public function up()
    {
        $this->getSchema()->table('users', function($table){
            $table->string('approve_token', 128)->nullable()->default(null)->change();
        });
        // set approve_token = null where it like '0' str or ''
        \Apps\ActiveRecord\User::where('approve_token', '=', '0')
            ->update('approve_token', null);
    }

    /**
     * @return void
     */
    public function down()
    {
        parent::down(); // TODO: Change the autogenerated stub
    }

    /**
     * Seed created table via up() method with some data
     * @return void
     */
    public function seed()
    {
        // TODO: Implement seed() method.
    }
}